name: Sample HTML Site Deploy to IIS
run-name: ${{ github.actor }} is deploying to IIS 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
        
    steps:
    - uses: actions/checkout@v2


    #### NOTE: These are extra steps needed to deploy to IIS Server ####
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with: 
    #       dotnet-version: '6.0.x'
        
    # - name: Build with dotnet
    #   shell: cmd
    #   run: dotnet build --configuration Release

    # - name: Publish with dotnet
    #   shell: cmd
    #   run:
    #     dotnet publish -c Release -o C:\Users\s0331983-a\myapp
    
    - name: Deploy to IIS Server
      shell: cmd
      run:
        xcopy /s /y ${{ github.workspace }}\* D:\web\sites\beta\tomeh