name: Sample HTML Site Deploy to IIS
run-name: ${{ github.actor }} is deploying to IIS 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
        
    steps:
    - uses: actions/checkout@v2

    # - name: Get current datetime
    #   id: datetime
    #   run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M:%S')"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
          dotnet-version: '6.0.x'
        
    - name: Build with dotnet
      shell: cmd
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      shell: cmd
      run:
        dotnet publish -c Release -o C:\Users\s0331983-a\myapp
    
    - name: Deploy to IIS Server
      shell: cmd
      run:
        iisreset /stop
        xcopy /s /y C:\Users\s0331983-a\myapp* D:\web\sites\beta\tomeh
        iisreset /start